### PR TITLE
Request placed into folders, Avoid duplicate request headers

### PR DESCRIPTION
**Pull request by salvo1404**
This fixes both issues.

### CODE REVIEW

**Comment by thecopy** [comment]
Thx

**Comment by salvo1404** [comment]
New release ?

**Comment by thecopy** [comment]
Uploaded new release on pypi

**Comment by thecopy** [comment]
If you want to make changes without a release, the source code is at `/usr/local/lib/python2.7/dist-packages/apiary2postman`

**Comment by salvo1404** [comment]
yes I know thank you, but I'm calling it in a bash script and I need to download it on the fly if it's not installed.

**Pull request merged**
